### ISSUE TITLE
Training and Retraining?

### ISSUE THREAD

**Issue by gaara100** [movehand/raisr#12]
Can this be trained more than once, for an improved model? Or does it overwrite any previous training and only use new data?

**Comment by movehand** [comment]
No, this can only be trained once currently. If many of you need this feature, I'll add it to the project! Thanks!

**Comment by gaara100** [comment]
I personally would love to see this feature implemented.

**Comment by lesseradmin** [comment]
Yeah this seems like a really cool feature to add to the project. That way more and more images can be added to the training set over time.

**Comment by movehand** [comment]
I've updated the project. Please refer to README for more information. Thanks!

**Comment by kvnloo** [comment]
Awesome job! Should this issue be closed now that this feature exists?
