### ISSUE TITLE
Resolution issue

### ISSUE THREAD

**Issue by xbaele** [movehand/raisr#15]
Hi, it works pretty well, thank you.  However I noticed the final resolution has one row and column less than expected (e.g. 256 in the source will give 511 in the result).  It's a problem to measure PSNR and SSIM.  Is it possible to fix that?  THX

**Comment by lesseradmin** [comment]
I had this issue as well. I was using an image that was 2560x1440 and the end result was 5119×2879.

**Comment by excllent123** [comment]
I had this issue as well.

**Comment by excllent123** [comment]
I  have modified code ,the problem is  
`    heightgridLR = np.linspace(0,heightLR-1,heightLR)
    widthgridLR = np.linspace(0,widthLR-1,widthLR)
    bilinearinterp = interpolate.interp2d(widthgridLR, heightgridLR, grayorigin, kind='linear')
    heightgridHR = np.linspace(0,heightLR-1,heightLR*2-1)
    widthgridHR = np.linspace(0,widthLR-1,widthLR*2-1)
    upscaledLR = bilinearinterp(widthgridHR, `heightgridHR)`
`
 heightgridLR = np.linspace(0,heightLR,heightLR)
    widthgridLR = np.linspace(0,widthLR,widthLR)
    bilinearinterp = interpolate.interp2d(widthgridLR, heightgridLR, grayorigin, kind='linear')
    heightgridHR = np.linspace(0,heightLR,heightLR*2)
    widthgridHR = np.linspace(0,widthLR,widthLR*2)
    upscaledLR = bilinearinterp(widthgridHR, `heightgridHR)
`
    the result is right ,but the PSNR is 34,53,but the paper is 35.9 for 2x，Can someone point out some problem?

**Comment by movehand** [comment]
@excllent123 Thank you for the effort! Quote from the paper:

> Bilinear upscaling by a factor of 2 in each axis. There are four types of pixels, denoted by P1-P4, corresponding to the four kernels that are applied during the bilinear interpolation.

So all the P1s from the upscaled image should be identical to the original pixels from the LR image. So that's why the code omits the rightmost column and the bottom row. If you print out the pixel value of the LR image and the upscaled image, you can see that every other pixel of the upscaled image is identical to the original LR.
```
LR
[[0.94117647 0.94509804 0.95294118 ... 0.9372549  0.9372549  0.93333333]
 [0.94117647 0.94509804 0.94901961 ... 0.9372549  0.9372549  0.93333333]
 [0.94117647 0.94509804 0.94901961 ... 0.94117647 0.9372549  0.92941176]
 ...
 [0.64313725 0.67058824 0.65882353 ... 0.7254902  0.71372549 0.74117647]
 [0.61176471 0.67058824 0.66666667 ... 0.71764706 0.69411765 0.69803922]
 [0.57254902 0.59215686 0.59607843 ... 0.69411765 0.67058824 0.61568627]]

Upscaled
[[0.94117647 0.94313725 0.94509804 ... 0.9372549  0.93529412 0.93333333]
 [0.94117647 0.94313725 0.94509804 ... 0.9372549  0.93529412 0.93333333]
 [0.94117647 0.94313725 0.94509804 ... 0.9372549  0.93529412 0.93333333]
 ...
 [0.61176471 0.64117647 0.67058824 ... 0.69411765 0.69607843 0.69803922]
 [0.59215686 0.61176471 0.63137255 ... 0.68235294 0.66960784 0.65686275]
 [0.57254902 0.58235294 0.59215686 ... 0.67058824 0.64313725 0.61568627]]
```
However, if you change it that way it will not follow that order.

My suggestion is to pad extra column and row at the right and bottom, so that it still follows that P1-P4 order.
```
Modified upscaled
[[0.94117647 0.94313725 0.94509804 ... 0.93529412 0.93333333 0.93333333]
 [0.94117647 0.94313725 0.94509804 ... 0.93529412 0.93333333 0.93333333]
 [0.94117647 0.94313725 0.94509804 ... 0.93529412 0.93333333 0.93333333]
 ...
 [0.59215686 0.61176471 0.63137255 ... 0.66960784 0.65686275 0.65686275]
 [0.57254902 0.58235294 0.59215686 ... 0.64313725 0.61568627 0.61568627]
 [0.57254902 0.58235294 0.59215686 ... 0.64313725 0.61568627 0.61568627]]
```

**Comment by movehand** [comment]
I pushed a testing version to the dev branch. Try it and tell me if it fits your needs!
@excllent123 Just a guess, try modifying the threshold for angle, strength, coherence in hashkey.py may generate a better PSNR. The original paper didn't mention the actual threshold, so the current threshold is just a trial and error result from me.

**Comment by excllent123** [comment]
@movehand Thanks for you kindly help.

**Comment by Maxetto** [comment]
@excllent123 Could you upload the filter on MEGA? I think I'm doing something wrong and Python is only using 1 core of my CPU, making it extremely long and painful to train.

**Comment by movehand** [comment]
@excllent123 Thank you for the feedback!
Please refer to the [contribution](https://github.com/movehand/raisr/blob/master/docs/CONTRIBUTING.md) page for further information. Basically, a pull request will do.
I haven't get into surveying the actual implementation of CT blending yet, sorry!

**Comment by movehand** [comment]
@excllent123 If you are interested in blending, take a look at [this](https://github.com/ranguwud/raisr) project. Hope it helps!
