### ISSUE TITLE
Let's get some more development for this project!

### ISSUE THREAD

**Issue by lesseradmin** [movehand/raisr#16]
@movehand this is an awesome project! I think that the best way to get it to grow is to add some development guidelines and some docs for other developers to hop on and help build new functionality. I think that sphinx would be a good place to get started so that docs can be created from parsing in-line documentation.

**Comment by movehand** [comment]
Thank you for the feedback! I'll get something started this weekend! Maybe some development guidelines or a checklist for unimplemented features.
