### ISSUE TITLE
Why the patchsize can't be Multiples of 10?

### ISSUE THREAD

**Issue by Rabbey** [movehand/raisr#19]
Error Code when patchsize=10 :
Q[angle,strength,coherence,pixeltype] += ATA
ValueError: operands could not be broadcast together with shapes (100,100) (121,121) (100,100)

Can't undestand why, anyone could help me ?

**Comment by movehand** [comment]
The project does not allow you to change the defined parameter in this stage, unexpected error may occur! (Unless you know exactly what you're doing) But if you want to change the patchsize for experimental purpose, change it to some odd number (patchsize=9 may be a better number in this case).
P.S. The patchsize indicates the operating area of a target pixel, so the target pixel should sit at the **center** of the patch. As a result, the patchsize will be an odd number.

**Comment by Rabbey** [comment]
Thanks for your answer!
