### ISSUE TITLE
2x - [width, height] -> [width*2-1, height*2-1]?

### ISSUE THREAD

**Issue by fstrugar** [movehand/raisr#21]
Hey, thanks for the great implementation of RAISR!

I wanted to compare it to some other solutions and noticed that the output images are [width*2-1, height*2-1] instead of 2x (so test.py with a 100x100 image will result in 199x199). I need to read the paper to get a better understanding but is this an expected result?

**Comment by movehand** [comment]
Please refer the thread #15 . Thanks!

**Comment by fstrugar** [comment]
Whoops, apologies! :)
