### ISSUE TITLE
Can you please share your trained filters file?

### ISSUE THREAD

**Issue by JustinhoCHN** [movehand/raisr#3]
I used the DIV2K data set as the training set, which contains 800 images, when I was training the model, it took too long to train every single image, about 4 mins/image. So I have to use 20 images instead, but it still took about one and a half hour, so may I ask if you can share your trained filters file please?

And my email is : justinho_chn@qq.com , I would be greatful if you send me the file, thanks.

**Comment by movehand** [comment]
I've contacted you via email. If you have any other questions, feel free to contact me.

**Comment by barretts** [comment]
Is there a reason you don't want to add the filter file to the repo? I have trained it on a few different data sets and I haven't been able to get the results I saw in the Google blog post at all. Have you had better luck? If you can send me the filter as well I'd appreciate it! bsonntag@gmail.com

**Comment by houxiaoxia1** [comment]
Hi，Thank you for your sharing. Could you share your trained filters file to me? I add some new images to BSDS500, and I want to compare the result with yours when I have finished the training. Thank you again. my email is 1390046334@qq.com.

**Comment by movehand** [comment]
@barretts @houxiaoxia1 Have send you guys the filter.

**Comment by Sachit-Menon** [comment]
Could you send me the filters as well? My email is sm568@duke.edu - thank you!

**Comment by movehand** [comment]
I've added the pretrained filter in the project. Please refer to README for more information. Thanks!
