### ISSUE TITLE
can you upload "filter" file?

### ISSUE THREAD

**Issue by cxf2015** [movehand/raisr#7]
can you upload "filter" file? use test

**Comment by movehand** [comment]
Please forgive me for not uploading the filter file. My intention is to let users train their own filter so I'm not considering to include the filter file in the repository. If you need the filter, can you give me your email so that I can send the file to you? Thank you!

**Comment by cxf2015** [comment]
@movehand cxfmaile@126.com
thank you

**Comment by movehand** [comment]
I put he filter in the project now, please refer to README for more information. Thanks!
