### ISSUE TITLE
Training Images vs Testing images

### ISSUE THREAD

**Issue by davideboschetto** [movehand/raisr#9]
Hi, nice and clean implementation, congrats.
I think the readme should explain a little bit more which kind of images to put in /train and /test (are these images the high resolution ones or the low resolution ones?)

Thank you for this!

**Comment by xiaofeiwu** [comment]
I have the same question, and would appreciate if anyone can give an answer.

**Comment by movehand** [comment]
Thank you @davideboschetto and @xiaofeiwu . Sorry for the late reply. I have added some explanation in readme, please check it out. Please feel free to let me know if you have any other questions!

**Comment by xiaofeiwu** [comment]
Thank you @movehand . It solved my question, and now I can run the training.
